"""add role_id to approval_step

Revision ID: b8ac66a4a73d
Revises: 4c43e53bb1cd
Create Date: 2026-01-31 16:31:52.861843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ac66a4a73d'
down_revision = '4c43e53bb1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('depreciation_records', ...) - Skipped because already exists
    with op.batch_alter_table('approval_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_approval_steps_role_id_roles', 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_steps', schema=None) as batch_op:
        batch_op.drop_constraint('fk_approval_steps_role_id_roles', type_='foreignkey')
        batch_op.drop_column('role_id')

    op.drop_table('depreciation_records')
    # ### end Alembic commands ###
